version: '3.8'

services:
  app:
    container_name: app_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      #- /usr/src/app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  app-network:
